// templates.js
// Each template must implement:
//   header()
//   membersHeader(count)
//   member(name, shipList)
//   membersFooter()
//   killsHeader()
//   killListSeparator(time, regions)
//   kill(zkillLink, shipName, iskMills)
//   loss(zkillLink, shipName, iskMills)
//   killsFooter()
//   statsHeader()
//   stats(iskGain, iskLoss)
//   statsFooter()
//   footer()
//
// Discord Markdown notes:
//   **text**   bold
//   *text*     italic
//   `text`     inline code / monospace
//   > text     block quote
//   URLs are auto-linked; wrapping in <url> suppresses the embed preview.
//   No colour support in standard Discord messages.
//   2000 character limit per message — split at fight separators if needed.

let discord = {
    header: () => "## 📋 After Action Report",

    membersHeader: (count) => `\n### 👥 Fleet Members *(${count} in fleet chat)*`,

    member: (name, ships) => {
        // -# renders as small subtext in Discord
        if (ships && ships.length > 0) {
            return `-# ${name} — ${ships.join(", ")}`;
        }
        return `-# ${name}`;
    },

    membersFooter: () => "",

    killsHeader: () => "\n### ⚔️ Kills & Losses",

    killListSeparator: (time, regions) =>
        `\n\`${time} EVE\`  **${regions.join(" / ")}**`,

    kill: (zkillLink, shipName, iskMills) =>
        `✅ **${shipName}** \`+${iskMills}m ISK\` — <${zkillLink}>`,

    loss: (zkillLink, shipName, iskMills) =>
        `❌ **${shipName}** \`-${iskMills}m ISK\` — <${zkillLink}>`,

    killsFooter: () => "",

    statsHeader: () => "\n### 📊 Stats",

    stats: (iskGain, iskLoss) => {
        let delta = iskGain - iskLoss;
        let efficiency = (iskGain + iskLoss) > 0
            ? ((iskGain * 100) / (iskGain + iskLoss)).toLocaleString("en-US", { maximumFractionDigits: 1 })
            : "N/A";
        let deltaSign = delta >= 0 ? "+" : "";
        let deltaEmoji = delta >= 0 ? "📈" : "📉";
        return `> 💰 ISK Destroyed: \`${iskGain.toLocaleString("en-US")}\`\n` +
               `> 💸 ISK Lost:      \`${iskLoss.toLocaleString("en-US")}\`\n` +
               `> ${deltaEmoji} ISK Delta:    \`${deltaSign}${delta.toLocaleString("en-US")}\`\n` +
               `> ⚖️  Efficiency:    \`${efficiency}%\``;
    },

    statsFooter: () => "",

    footer: () => "\n*Generated by EveRoamReport*"
};

window.templates = {
    discord: discord
};